name: CI Frontend

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Check formatting with Prettier
      run: yarn format:check client
    - name: Check quality with ESLint
      run: yarn lint client
    - name: Check types compile
      run: yarn type-check client
    - name: Check tests pass
      run: yarn test client
    - name: Check app builds
      run: yarn build client